### ISSUE TITLE
Eclipse V18

### ISSUE THREAD

**Issue by ste-agolabs** [ddicostanzo/CC-Gen#2]
Hi Dominic, is CC Generator available for Eclipse V18?
Thanks

**Comment by ddicostanzo** [comment]
Hi there, we are on v18 and this script worked without recompiling. Are you running into an issue?

**Comment by ste-agolabs** [comment]
Ok thanks I'll try it and let you know. Thanks

Il mer 18 dic 2024, 16:26 Dominic DiCostanzo ***@***.***> ha
scritto:

**Comment by ste-agolabs** [comment]
Hi Dominic, I downloaded the source code (you do not provide the compiled script dll right?) but using Visual Studio 2022 I cannot compile the solution because some files (like AriaConnection.cs) are missing. Am i doing something wrong?
Thanks!

**Comment by ddicostanzo** [comment]
When you downloaded the source did you pull from the "releases" section?
The OSU Helpers are required for building the application, and sounds like
those are missing from your build.
Written on my mobile device. Please excuse any typographical errors.

**Comment by ste-agolabs** [comment]
Hi Dominic, I downloaded from GitHub/releases the zip file. The solution
contains the OSU Helpers drawer but it seems some helper is missing. Can
you please check? Thanks a lot
Stefano

Il gio 19 dic 2024, 11:47 Dominic DiCostanzo ***@***.***> ha
scritto:

> When you downloaded the source did you pull from the "releases" section?
> The OSU Helpers are required for building the application, and sounds like
> those are missing from your build.
> Written on my mobile device. Please excuse any typographical errors.
>

**Comment by ddicostanzo** [comment]
Hi Stefano, if you look in the project OSU_Helpers_Public, there are some files "Aria_Connection" among them that were purposefully excluded from the uploaded version. They show as dotted box outlines and aren't able to be found. If you exclude those from the project and try to build, I was able to get the released version to build. You can also build against the v18 ESAPI DLLs if you prefer. Hope this helps. I'll work on updating the release to rectify the problem.

**Comment by ddicostanzo** [comment]
Hi Stefano, I've updated the release to v1.0.1 to exclude the files and it should be able to be built now without issues. Thanks for bringing this up.

**Comment by ste-agolabs** [comment]
Thanks a lot Dominic I'll check that once I'm back to work after holidays.
I wish you a merry Christmas! Cheers

Il gio 19 dic 2024, 15:51 Dominic DiCostanzo ***@***.***> ha
scritto:

**Comment by ddicostanzo** [comment]
Thanks, same to you!
